# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# Docker-Services-CLI is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

services:
  redis:
    image: redis
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: "unless-stopped"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DB}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    ports:
      - "3306:3306"
  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER=${POSTGRESQL_USER}"
      - "POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}"
      - "POSTGRES_DB=${POSTGRESQL_DB}"
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${ELASTICSEARCH_VERSION}
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - "path.repo=['/opt/elasticsearch/backup']"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    ports:
      - "9200:9200"
      - "9300:9300"
  rabbitmq:
    image: rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
